// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'views/base/collection-view', 'views/topic/item', 'views/loading', 'text!views/templates/topic/list.html'], function(Chaplin, CollectionView, TopicItemView, LoadingView, template) {
  'use strict';
  var TopicListView, _ref;
  return TopicListView = (function(_super) {
    __extends(TopicListView, _super);

    function TopicListView() {
      _ref = TopicListView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    TopicListView.prototype.itemView = TopicItemView;

    TopicListView.prototype.listSelector = '.topic-list';

    TopicListView.prototype.template = template;

    TopicListView.prototype.addCollectionListeners = function() {
      TopicListView.__super__.addCollectionListeners.apply(this, arguments);
      this.subscribeEvent('before:fetch', function() {
        return this.loadingView = new LoadingView({
          message: '主题加载中...',
          container: $('.list')
        });
      });
      return this.subscribeEvent('after:fetch', function() {
        if (this.loadingView != null) {
          this.loadingView.dispose();
        }
        this.loadingView = null;
        return this.loading = false;
      });
    };

    TopicListView.prototype.render = function() {
      var _this = this;
      TopicListView.__super__.render.apply(this, arguments);
      this.loading = false;
      return $(window).scroll(function() {
        if ($(window).scrollTop() >= $(document).height() - $(window).height() && !_this.loading) {
          _this.loading = true;
          return _this.collection.hasNextPage() && _this.collection.nextPage();
        }
      });
    };

    TopicListView.prototype.setActiveTab = function(tab) {
      return this.$(".tabs li." + tab).addClass('active');
    };

    return TopicListView;

  })(CollectionView);
});
