// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/page-view', 'views/post/list', 'text!views/templates/topic/show.html'], function(PageView, PostListView, template) {
  'use strict';
  var TopicShowView, _ref;

  return TopicShowView = (function(_super) {
    __extends(TopicShowView, _super);

    function TopicShowView() {
      _ref = TopicShowView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    TopicShowView.prototype.template = template;

    TopicShowView.prototype.regions = {
      '.post-list-view': 'posts'
    };

    TopicShowView.prototype.events = {
      'click .topic .action-like': function(e) {
        var $o;

        e.preventDefault();
        $o = $(e.currentTarget);
        return this.model.like({
          success: function(resp) {
            $o.tooltip({
              trigger: 'hover',
              title: '已标记为喜欢'
            });
            return $o.tooltip('show');
          },
          error: function(xhr) {
            $o.tooltip({
              trigger: 'hover',
              title: xhr.responseText
            });
            return $o.tooltip('show');
          }
        });
      },
      'click .topic .action-watch': function(e) {
        var $o;

        e.preventDefault();
        $o = $(e.currentTarget);
        return this.model.watch({
          success: function(resp) {
            $o.tooltip({
              trigger: 'hover',
              title: '已关注'
            });
            return $o.tooltip('show');
          },
          error: function(xhr) {
            $o.tooltip({
              trigger: 'hover',
              title: xhr.responseText
            });
            return $o.tooltip('show');
          }
        });
      },
      'click .topic .action-reply': function(e) {
        var $o;

        e.preventDefault();
        return $o = $(e.currentTarget);
      }
    };

    TopicShowView.prototype.render = function() {
      TopicShowView.__super__.render.apply(this, arguments);
      this.postListView = new PostListView({
        model: this.model,
        collection: this.model.fetchPosts(),
        region: 'posts'
      });
      this.postListView.topic = this.model;
      return this.subview('postListView', this.postListView);
    };

    return TopicShowView;

  })(PageView);
});
