// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/page-view', 'text!views/templates/node/list.html'], function(PageView, template) {
  'use strict';
  var NodeListView, _ref;

  return NodeListView = (function(_super) {
    __extends(NodeListView, _super);

    function NodeListView() {
      _ref = NodeListView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    NodeListView.prototype.template = template;

    return NodeListView;

  })(PageView);
});
