// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'text!views/templates/node/selector.html', 'css!components/chosen/chosen/chosen.css', 'components/chosen/chosen/chosen.jquery'], function(View, template) {
  'use strict';
  var NodeSelectorView, _ref;

  return NodeSelectorView = (function(_super) {
    __extends(NodeSelectorView, _super);

    function NodeSelectorView() {
      _ref = NodeSelectorView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    NodeSelectorView.prototype.template = template;

    NodeSelectorView.prototype.render = function() {
      NodeSelectorView.__super__.render.apply(this, arguments);
      return this.$('.chzn-select').chosen({
        no_results_text: '节点不存在'
      });
    };

    return NodeSelectorView;

  })(View);
});
