// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/collection-view', 'views/user/home/post-item', 'text!views/templates/user/home/post.html'], function(CollectionView, PostItemView, template) {
  'use strict';
  var HomePostView, _ref;
  return HomePostView = (function(_super) {
    __extends(HomePostView, _super);

    function HomePostView() {
      _ref = HomePostView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    HomePostView.prototype.listSelector = '.post-item-region';

    HomePostView.prototype.fallbackSelector = '.empty-region';

    HomePostView.prototype.itemView = PostItemView;

    HomePostView.prototype.template = template;

    return HomePostView;

  })(CollectionView);
});
