// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'text!views/templates/user/home/post-item.html'], function(View, template) {
  'use strict';
  var PostItemView, _ref;
  return PostItemView = (function(_super) {
    __extends(PostItemView, _super);

    function PostItemView() {
      _ref = PostItemView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PostItemView.prototype.tagName = 'tr';

    PostItemView.prototype.template = template;

    return PostItemView;

  })(View);
});
