// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'text!views/templates/user/home/topic.html'], function(View, template) {
  'use strict';
  var UserTopicView, _ref;
  return UserTopicView = (function(_super) {
    __extends(UserTopicView, _super);

    function UserTopicView() {
      _ref = UserTopicView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    UserTopicView.prototype.tagName = 'tr';

    UserTopicView.prototype.template = template;

    return UserTopicView;

  })(View);
});
