// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'text!views/templates/post/item.html'], function(View, template) {
  'use strict';
  var PostItemView, _ref;

  return PostItemView = (function(_super) {
    __extends(PostItemView, _super);

    function PostItemView() {
      _ref = PostItemView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PostItemView.prototype.template = template;

    PostItemView.prototype.events = {
      'click .post .action-like': function(e) {
        var $o;

        e.preventDefault();
        $o = $(e.currentTarget);
        return this.model.like({
          success: function(resp) {
            $o.tooltip({
              trigger: 'hover',
              title: '已标记为喜欢'
            });
            return $o.tooltip('show');
          },
          error: function(xhr) {
            $o.tooltip({
              trigger: 'hover',
              title: xhr.responseText
            });
            return $o.tooltip('show');
          }
        });
      },
      'click .post .action-reply': function(e) {
        e.preventDefault();
        return console.debug('reply');
      }
    };

    return PostItemView;

  })(View);
});
