// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/page-view', 'models/topics', 'views/user/home/topic', 'text!views/templates/user/home.html'], function(PageView, Topics, HomeTopicView, template) {
  'use strict';
  var UserHomeView, _ref;
  return UserHomeView = (function(_super) {
    __extends(UserHomeView, _super);

    function UserHomeView() {
      _ref = UserHomeView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    UserHomeView.prototype.regions = {
      '.home-list-region': 'home-list-region'
    };

    UserHomeView.prototype.template = template;

    return UserHomeView;

  })(PageView);
});
