// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'text!views/templates/user/notifications/item.html'], function(View, template) {
  'use strict';
  var NotificationItemView, _ref;
  return NotificationItemView = (function(_super) {
    __extends(NotificationItemView, _super);

    function NotificationItemView() {
      _ref = NotificationItemView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    NotificationItemView.prototype.template = template;

    NotificationItemView.prototype.events = {
      'click .unread': function(e) {
        e.preventDefault();
        return this.model.read({
          success: function(resp) {
            return console.debug('123');
          },
          error: function(resp) {
            return console.debug(resp.responseText);
          }
        });
      }
    };

    return NotificationItemView;

  })(View);
});
