// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['controllers/base/controller', 'models/nodes', 'views/node/list'], function(Controller, Nodes, NodeListView) {
  'use strict';
  var NodeController, _ref;
  return NodeController = (function(_super) {
    __extends(NodeController, _super);

    function NodeController() {
      _ref = NodeController.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    NodeController.prototype.list = function() {
      this.collection = new Nodes;
      this.view = new NodeListView({
        collection: this.collection
      });
      return this.collection.fetch();
    };

    return NodeController;

  })(Controller);
});
