// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['models/base/collection', 'models/notification'], function(Collection, Notification) {
  'use strict';
  var Nodes, _ref;
  return Nodes = (function(_super) {
    __extends(Nodes, _super);

    function Nodes() {
      _ref = Nodes.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Nodes.prototype.model = Notification;

    Nodes.prototype.urlPath = function() {
      return '/notifications';
    };

    return Nodes;

  })(Collection);
});
