// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['models/base/pageable-collection', 'models/topic'], function(PageableCollection, Topic) {
  'use strict';
  var Topics, _ref;
  return Topics = (function(_super) {
    __extends(Topics, _super);

    function Topics() {
      _ref = Topics.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Topics.prototype.model = Topic;

    Topics.prototype.urlPath = function() {
      return '/topics';
    };

    return Topics;

  })(PageableCollection);
});
