// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'text!views/templates/site.html'], function(View, template) {
  'use strict';
  var SiteView, _ref;
  return SiteView = (function(_super) {
    __extends(SiteView, _super);

    function SiteView() {
      _ref = SiteView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    SiteView.prototype.el = 'body';

    SiteView.prototype.regions = {
      '#topnav .top-panel': 'top-panel',
      '#container': 'main'
    };

    SiteView.prototype.template = template;

    return SiteView;

  })(View);
});
