// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'views/base/view', 'text!views/templates/top-panel.html'], function(Chaplin, View, template) {
  'use strict';
  var TopPanelView, _ref;

  return TopPanelView = (function(_super) {
    __extends(TopPanelView, _super);

    function TopPanelView() {
      _ref = TopPanelView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    TopPanelView.prototype.el = '.top-panel';

    TopPanelView.prototype.autoRender = true;

    TopPanelView.prototype.region = 'top-panel';

    TopPanelView.prototype.template = template;

    TopPanelView.prototype.initialize = function() {
      return this.subscribeEvent('!user:refresh', this.render);
    };

    return TopPanelView;

  })(View);
});
